#!/usr/bin/env python

# https://gist.github.com/crazyhottommy/7255638#file-reverse_complement-py

def revcomp(seq):
    for base in seq:
        if base not in 'ATCGatcg':
            print "Error: NOT a DNA sequence"
            return None
    seq1 = 'ATCGTAGCatcgtagc'
    seq_dict = { seq1[i]:seq1[i+4] for i in range(16) if i < 4 or 8<=i<12 }
    return "".join([seq_dict[base] for base in reversed(seq)])

import sys

if len(sys.argv) == 1:
    print "usage:", sys.argv[0], "[DNA sequence] # produces reverse complement on stdout"
    exit(1)

print revcomp(sys.argv[1])

